# possible values: auto, full, compact
style = "compact"

# date format used, either "us" or "uk"
dialect = "us"

# address of the sync server
sync_address = "http://server:7070"

# enable or disable automatic sync
auto_sync = true

# how often to sync history. note that this is only triggered when a command is
# ran, so sync intervals may well be longer. set it to 0 to sync each command
sync_frequency = "5m"

# enable or disable automatic update checks
update_check = false

# Search interface styling
inline_height=20
show_help = false
filter_mode_shell_up_key_binding = "session"

# Typically I want shell history from this machine, Can always tap C-R to get
# history from other machines
filter_mode = "host"

# Select query when exiting
exit_mode = "return-query"
